version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
    # environment:
    #   MYSQL_ROOT_PASSWORD: example
    # user: "1000:1000"
    volumes:
      - /home/anying/Workspace/GoReactResourceManagementMysqlDatas:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword123"]
      timeout: 5s
      retries: 100
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - 8088:8080
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy